steps:
  - label: ":python: Generate sentence"
    command: |
      python install .
      python -c "import loremipsum; print(loremipsum.sentence(max_char=20))"
    plugins:
      - docker#v5.13.0:
          image: "python:3.13"
    agents:
      queue: "self-hosted"
    
